name: Feature request
description: Suggest a new feature
labels: ['feature']
assignees:
  - delta1
body:
  - type: input
    id: project
    attributes:
      label: "Project"
      description: "Which subproject or area"
      placeholder: "core | compiler | vscode | book | tests | other"
    validations:
      required: true
  - type: textarea
    id: feature-description
    attributes:
      label: "Describe the feature"
      description: "A description of what you would like to see in the project"
    validations:
      required: true
